name: blur_matrix
description: A widget that draws a matrix of colors gradients. Could be also animated. Could be a starting point for nice visuals.
version: 1.0.0+1
author: Marco Bavagnoli <marcobavagnolidev@gmail.com>
homepage: https://github.com/alnitak/blur_matrix

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
